### ISSUE TITLE
Initialization problem

### ISSUE THREAD

**Issue by walwalwalides** [HemulGM/FMXAudio#1]
TFMXPlayer : Get problem by initialization the component 
Don't know if i have the wrong bass.dll
But it's doesn't work for me
Think for this nice work !

**Comment by HemulGM** [comment]
Is it possible in more detail? It is possible to display an error code through the LastError of the component.

**Comment by HemulGM** [comment]
I added a working example and added the libraries used.

**Comment by walwalwalides** [comment]
Think's men 👍 I appreciate it alot , i will check it today ,if it work ...,
Actually i also working in a project in music area.
And I also think that many nice stuff can be done !, so keep going ,stay Positiv and Safe 🥇
